apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-clamav
  namespace: prod
spec:
  dnsNames:
  - clamav.bred.team
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-kotiki
  secretName: prod-clamav
  usages:
  - digital signature
  - key encipherment

