.build:
  script:
    #- export STACKLOG_PATH=/workspace/kaniko.slog
    - echo -e "\e[33m$WHAT_IS_STAND" && echo -e "\e[33m$STACKLOG_PATH"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - echo -e "\e[33mExample   $CI_REGISTRY_IMAGE/name_service:$WHAT_IS_STAND-task_number-$CI_JOB_ID"
    - |
      for app in $(ls -p cmd  | grep -i '/')
      do
       service=$(echo $app | cut -d'/' -f1)
       echo $service
       name_ufl=$(echo $service | awk '{ print toupper( substr( $0, 1, 1 ) ) substr( $0, 2 ); }')
       echo $name_ufl
       /kaniko/executor \
       --log-timestamp \
       --verbosity debug \
       --context $CI_PROJECT_DIR \
       --dockerfile $CI_PROJECT_DIR/.dockerfiles/Service$name_ufl.dockerfile \
       --destination $CI_REGISTRY_IMAGE/$service:$WHAT_IS_STAND-task_number-v1.1.1 \
       --push-retry=3
      done
  #    - /kaniko/executor
  #      --snapshotMode=redo
  #      --cache=true
  #      --cache-ttl=1h
  #      --context $CI_PROJECT_DIR
  #      --dockerfile $CI_PROJECT_DIR/.dockerfiles/ServiceOmnitool.dockerfile
  #      --destination $CI_REGISTRY_IMAGE/ServiceOmniTool:$WHAT_IS_STAND-task_number-$CI_JOB_ID --push-retry=3

  allow_failure: true
